# For Vagrant+QEMU: primary deployment is `vagrant up` (uses ansible provisioner).
# This inventory is for manual re-runs after VM is up:
#   vagrant ssh-config > .vagrant/ssh-config
#   ansible-playbook playbooks/deploy.yml --ssh-extra-args="-F .vagrant/ssh-config"
#
# For production: replace ansible_host/port/key with your server details.
all:
  hosts:
    mtproxy-server:
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/qemu/private_key
      ansible_become: yes
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
